services:
  - type: web
    name: datanetra-ai
    runtime: python
    pythonVersion: "3.11.0"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
